repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.0
    hooks:
      - id: pylint
        args: ["app/"]
        additional_dependencies:
          - fastapi
          - requests
          - jinja2

