name: Docker CI Build with Trivy Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/currency-converter-app:latest .

      - name: Run Trivy vulnerability scan (fail on High and Critical)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/currency-converter-app:latest'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true
          format: 'table'

      - name: Push Docker image to Docker Hub (only if Trivy passed)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/currency-converter-app:latest
