name: Docker Build, Trivy Scan, and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Step 3: Set up Docker Hub credentials
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/currency-converter-app:latest .

      # ✅ Step 5: Install Trivy vulnerability scanner
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # ✅ Step 6: Trivy Image Scan (Fail if any HIGH or CRITICAL vulnerabilities)
      - name: Run Trivy Vulnerability Scan
        run: trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ secrets.DOCKERHUB_USERNAME }}/currency-converter-app:latest

      # ✅ Step 7: Push Docker image to Docker Hub (ONLY IF Trivy passed)
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/currency-converter-app:latest
